backtest:
  end_date: '2025-09-30'
  report_dir: reports/
  start_date: '2025-09-01'
  use_hybrid_confirm: true
confirm:
  delta:
    ret_min: 0.0001
    spread_drop: 0.0001
    zvol_min: 0.1
  exclude_cand_point: true
  min_axes: 2
  persistent_n: 22
  pre_window_s: 5
  require_price_axis: false
  spread_max: 0.03
  vol_z_min: 1.0
  window_s: 15
cpd:
  cooldown_s: 3.0
  price:
    h_mult: 6.0
    k_sigma: 0.7
    min_pre_s: 10
  use: false
  volume:
    delta: 0.05
    lambda: 6.0
detection:
  min_axes_required: 2
  score_threshold: 2.0
  ticks_min: 2
  vol_z_min: 2.0
  weights:
    accel: 1.0
    ret: 1.0
    ticks: 0.5
    z_vol: 1.0
features:
  long_window: 1800
  rolling:
    price_window: 600
    vol_window: 300
  short_window: 60
logging:
  file_rotation: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
ml:
  enabled: true
  model_path: models/onset_model.pkl
  threshold: 0.6
  use_hybrid_confirm: true
onset:
  confirm_window_s: 12
  friction:
    spread_narrowing_pct: 0.6
  participation:
    z_vol_threshold: 2.5
  refractory_s: 20
  score_threshold: 2.0
  speed:
    ret_1s_threshold: 0.002
  thresholds:
    min_return_pct: 0.005
    min_volume_z: 1.5
    percentile: 95
  weights:
    friction: 0.2
    participation: 0.4
    speed: 0.4
paths:
  data_clean: data/clean
  data_events: data/events
  data_features: data/features
  data_labels: data/labels
  data_raw: data/raw
  logs: logs
  plots: reports/plots
  reports: reports
refractory:
  duration_s: 45
  extend_on_confirm: true
segmenter:
  dd_stop_pct: 0.012
  max_hold_s: 180
  vol_norm_z: 1.0
session:
  lunch_end: '13:00'
  lunch_start: '12:00'
  market_close: '15:30'
  market_open: 09:00
  timezone: Asia/Seoul
time:
  epoch_unit: ms
  timezone: Asia/Seoul
trading:
  live:
    account_no: '1234567890'
    api: dummy
    risk_limit_pct: 0.05
  simulator:
    capital: 10000000
    fee_rate: 0.0005
    hold_time_s: 60
    slippage: 0.0002
    stop_loss_pct: 0.01
    take_profit_pct: 0.02
visual:
  debug_labels: false
  mode: point
  show_stages: true
  timeline_panel: true
volume:
  is_cumulative: true
  roll_window_s: 300
